name: Github actions

on: [push]

jobs:
  github-training:
   runs-on: ubuntu-latest
   steps:
    - name: checkout the repo
      uses: actions/checkout@v4

    - name: run node app
      run: node app.js
