name: a simple workflow

on: push

jobs:
  node-strategy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [6,7,8]
      fail-fast: true
    steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: "${{ matrix.node_version }}"
    - name: get node version
      run: node -v
     