name: a simple workflow

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [6,7,8]
      fail-fast: true
    steps:
     - name: hello
       run: node -v
     