name: a simple workflow

on: push

env:
  GREET: "Hola!"
  BYE: "Chao!"
jobs:
  node-strategy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [6,7,8]
      fail-fast: true
    steps:
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: "${{ matrix.node_version }}"
    - name: get node version
      run: node -v
      
    - name: Greeting
      run: |
        echo $GREET
        echo $BYE
     