name: Shell commands
on: [push]

jobs:
 run-shell-commands:
   runs-on: ubuntu-latest
   steps:
    - name: echo a string
      run: echo 'hello world'
    - name: run a scrip
      run: |
        node -v
        npm -v

    - name: display a greeting
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with:
       who-to-greet: Bharat

    - name: print action output
      run: echo "${{ steps.greet.outputs.time }}"
